# Configuration for auto-assign action
# Automatically assigns reviewers and assignees to PRs and issues

# Add reviewers to pull requests
addReviewers: true

# Add assignees to pull requests and issues
addAssignees: true

# List of reviewers to be added to pull requests (GitHub usernames)
reviewers:
  - fernandoduarte  # Add the main maintainer

# List of assignees to be added to pull requests and issues
assignees:
  - fernandoduarte  # Add the main maintainer

# Number of reviewers to add to each pull request
numberOfReviewers: 1

# Number of assignees to add to each pull request/issue
numberOfAssignees: 1

# Skip adding reviewers if the PR is in draft mode
skipDraft: true

# Skip adding reviewers if the PR author is in the reviewers list
skipKeywords:
  - wip
  - draft
  - "[skip assign]"

# Use review groups for team-based assignment (if using teams)
useReviewGroups: false

# Use assignee groups for team-based assignment (if using teams)
useAssigneeGroups: false
