# NOTE: Bandit security checks are also covered by Ruff's S-prefix rules
# This file is maintained for compatibility and additional security scanning
overrides:
  - id: "B101"
    paths:
      - "tests/*"

skips: ["B101", "B404", "B603"]

# Exclude directories from scanning
exclude_dirs:
  - "/tests/"
  - "/.venv/"
  - "/venv/"
  - "/.mypy_cache/"
  - "/.pytest_cache/"

# Set confidence level
confidence: MEDIUM
