[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "china_data"
version = "0.1.0"
description = "China economic data downloader and processor"
requires-python = ">=3.8"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --strict-markers --tb=short"

[tool.setuptools]
packages = ["utils", "tests"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.md", "*.json"] 