name: Bug Report
description: File a bug report to help us improve the China Data Processing Pipeline
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Data Downloader
        - Data Processor
        - Economic Indicators Calculation
        - Data Validation
        - Output Generation
        - Configuration
        - Testing
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error...
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or output
      placeholder: |
        Paste error logs here...
      render: shell
      
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      options:
        - "3.8"
        - "3.9" 
        - "3.10"
        - "3.11"
        - "Other (specify in additional context)"
    validations:
      required: true
      
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - "Windows"
        - "macOS"
        - "Linux (Ubuntu)"
        - "Linux (CentOS/RHEL)"
        - "Linux (Other)"
        - "Other (specify in additional context)"
    validations:
      required: true
      
  - type: textarea
    id: data-context
    attributes:
      label: Data Context
      description: Information about the data being processed when the bug occurred
      placeholder: |
        - Year range: 
        - Data sources affected:
        - Input file size:
        - Any custom parameters used:
        
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Virtual environment: Yes/No
        - Package versions (run `pip freeze`):
        - Any custom configuration:
        
  - type: checkboxes
    id: data-sensitivity
    attributes:
      label: Data Sensitivity
      description: Please confirm about data sensitivity
      options:
        - label: I have not included any sensitive or proprietary economic data in this report
          required: true
        - label: The bug is reproducible with sample/test data
          required: false
          
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if applicable)
        - Related issues
        - Workarounds tried
        - Impact on analysis results 