name: 'Auto Assign'

on:
  pull_request:
    types: [opened, ready_for_review, reopened]
  issues:
    types: [opened]

concurrency:
  group: auto-assign-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR/Issue
        uses: kentaro-m/auto-assign-action@v2.0.0
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto-assign-config.yml"

  add-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Auto-label PR based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"

  pr-size-labeler:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Label PR by size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: 10
          s_label: 'size/S'
          s_max_size: 100
          m_label: 'size/M'
          m_max_size: 500
          l_label: 'size/L'
          l_max_size: 1000
          xl_label: 'size/XL'
