name: CI with UV
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write
  checks: write

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test-uv:
    name: Test with UV
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          # Reduce matrix for faster CI
          - os: windows-latest
            python-version: "3.13"
          - os: macos-latest
            python-version: "3.13"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python with UV
        run: uv python install ${{ matrix.python-version }}

      - name: Create virtual environment
        run: uv venv --python ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Create output directory
        run: mkdir -p output

      - name: Run tests with UV
        run: uv run pytest tests/ -v --tb=short --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  lint-uv:
    name: Lint with UV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python with UV
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --dev

      - name: Run Ruff linting
        run: uv run ruff check . --output-format=github

      - name: Run Ruff formatting check
        run: uv run ruff format --check .

      - name: Run mypy type checking
        run: uv run mypy china_data_processor.py china_data_downloader.py || true

  security-uv:
    name: Security Scan with UV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python with UV
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --dev

      - name: Run security checks
        run: |
          uv run ruff check . --select=S --output-format=github
          uv run bandit -r . -f json -o bandit-report.json --exclude "./venv/*,./tests/*" || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports-uv
          path: bandit-report.json
